# Generated by Django 2.2.4 on 2022-05-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20220516_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
